- name: Update APT servers
  hosts: apt_servers
  become: true
  gather_facts: false
  tasks:
    - name: Update all packages
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: true
