- name: Local example
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Display message
      ansible.builtin.command: echo "Ansible ran successfully"
      register: message

    - name: Show message
      ansible.builtin.debug:
        var: message.stdout
