- name: Exemplo local
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Exibir mensagem
      ansible.builtin.command: echo "Ansible executado com sucesso"
      register: mensagem

    - name: Mostrar mensagem
      ansible.builtin.debug:
        var: mensagem.stdout
